on:
  release:
    types: [created]
    
  workflow_dispatch:
    
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: windows-2019
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - run: npm install
      - run: npm audit fix
      - run: npm audit
      - run: npm install -g pkg
      - run: mkdir dist
      - run: pkg index.js --targets node14 --compress GZip -o .dist/test > ./test.log
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'test*'
